package com.csidigital.rh.shared.enumeration;

public enum ContractTitle {

    PERMANENT_EMPLOYMENT_CONTRACT, FIXED_TERM_EMPLOYMENT_CONTRACT,
    PROFESSIONALIZATION_CONTRACT,
    TEMPORARY_WORK_CONTRACT,
    PART_TIME_WORK_CONTRACT,
    SEASONAL_WORK_CONTRACT,
    STUDY_CONTRACT
}
